### PR TITLE
Add linters and setup CI

### PR DESCRIPTION
**Pull request by ezhlobo**

### CODE REVIEW

**Comment by ezhlobo** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;UkOBGBUg&#x2F;320-as-a-developer-i-want-that-all-developers-follow-the-same-code-style"> As a developer, I want that all developers follow the same code style</a>

**Comment by ezhlobo** [comment]
@Proghat sorry, not sure what do you mean. Probably because you lost highlight.

**Comment by Proghat** [comment]
Yeah, the keyboard on my phone doesn't allow me to type backtick "`". So I'm asking about transition from
```css
.selector {
  color: $gray;
  }
```
to
```css
.selector {
  color: $gray;
}
```

**Comment by ezhlobo** [comment]
@Proghat yes, because it's necessary to explain for everyone why we follow this styling. Also no one linter supports my favourite syntax :(. So I decided to don't follow it.

**Comment by Proghat** [comment]
@ezhlobo, ok, got it (hug).

Can you please rebase this branch on top of "dev"?

**Comment by ezhlobo** [comment]
@Proghat I can't rebase because here is a lot of conflicts. I'll make this branch up-to-date as soon as possible

**Comment by Proghat** [comment]
@ezhlobo, huh. So squashing commits before merging them has a serious downside.

**Comment by ezhlobo** [comment]
@Proghat I don't think that it's a normal case. Let's try to live with squashing and I believe that we will happy with it.

**Pull request merged**
