### PR TITLE
Admin clean-up

### PR DESCRIPTION
**Pull request by solopiy**

### CODE REVIEW

**Comment by solopiy** [comment]
[When I am on the admin panel I wanna be sure that admin code is cool and fully refactored](https://trello.com/c/xUyv8rVi/347-when-i-am-on-the-admin-panel-i-wanna-be-sure-that-admin-code-is-cool-and-fully-refactored)

**Comment by UladzislauCharneny** [comment]
Мне нотификации на почту приходят о ваших ПР :)

**Comment by solopiy** [comment]
@UladzislauCharneny это opensource проект. Отключи увеломления :)

**Comment by solopiy** [comment]
[When I visit admin panel list of posts page, posts with long names should look good](https://trello.com/c/4vr1IOd4/361-when-i-visit-admin-panel-list-of-posts-page-posts-with-long-names-should-look-good)

**Comment by solopiy** [comment]
[When I visit admin panel edit post page, I should choose publish date via date picker instead of simple buttons](https://trello.com/c/ZbVQ3E6V/363-when-i-visit-admin-panel-edit-post-page-i-should-choose-publish-date-via-date-picker-instead-of-simple-buttons)

**Comment by solopiy** [comment]
[When I visit admin panel edit post page, I should be informed - is post visible or not](https://trello.com/c/ifG6AA8B/362-when-i-visit-admin-panel-edit-post-page-i-should-be-informed-is-post-visible-or-not)

**Comment by solopiy** [comment]
[When I visit admin panel edit post page and I am creating new author - I should be informed that this author was added successfully](https://trello.com/c/jzQCaZNz/364-when-i-visit-admin-panel-edit-post-page-and-i-am-creating-new-author-i-should-be-informed-that-this-author-was-added-successfull)

**Comment by solopiy** [comment]
[Fix bug connected with the removing bold text in AlloyEditor](https://trello.com/c/rYbegOZE/366-fix-bug-connected-with-the-removing-bold-text-in-alloyeditor)

**Comment by solopiy** [comment]
[Add ability for AlloyEditor to make lists autamitally](https://trello.com/c/NJguNffN/367-add-ability-for-alloyeditor-to-make-lists-autamitally)

**Pull request merged**
