### PR TITLE
Setup CircleCI correctly

### PR DESCRIPTION
**Pull request by ezhlobo**

### CODE REVIEW

**Comment by ezhlobo** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;UkOBGBUg&#x2F;320-as-a-developer-i-want-that-all-developers-follow-the-same-code-style"> As a developer, I want that all developers follow the same code style</a>

**Comment by Proghat** [comment]
+15 -20. It's very clear, please merge :shipit:.

**Comment by ezhlobo** [comment]
@Proghat don't forget to approve here ;)

**Comment by ezhlobo** [comment]
@Proghat github still has a bug with approving PRs. Could you please turn off that checking for now?

**Comment by Proghat** [comment]
@ezhlobo, done.

**Pull request merged**
